# Generated by Django 5.0.5 on 2024-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='heurrestante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
